# Generated by Django 3.1.1 on 2022-03-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='resolu',
            field=models.BooleanField(default=True),
        ),
    ]
