# Generated by Django 3.1.1 on 2022-03-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etateau',
            name='choix',
            field=models.CharField(blank=True, choices=[('POTABLE', 'P'), ('DANGE', 'D')], default=None, max_length=20, null=True),
        ),
    ]
